### ISSUE TITLE
ImportError: No module named main_sim

### ISSUE THREAD

**Issue by ZZcat** [openworm/sibernetic#139]
Someones-Mac:sibernetic-development stea$ ./Release/Sibernetic -f worm
[debug] pName = "main_sim"
[debug] PyPath = "/usr/local/lib/python2.7/site-packages:./sibernetic_NEURON:./src:./src:./src:/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload"
ImportError: No module named main_sim
Sibernetic(27995,0x7fffe96243c0) malloc: *** error for object 0x5000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
Someones-Mac:sibernetic-development stea$

**Comment by lungd** [comment]
@ZZcat thank you for reporting this issue.
Some files like main_sim.py are now located in the root directory so you have to add that directory to PYTHONPATH instead of 'src/'
You should be able to run Sibernetic after running `export PYTHONPATH=$PYTHONPATH:.`
I already updated the README accordingly.
